import type { Metadata } from "next";
import "./globals.css";
import ToasterProvider from './providers/ToasterProvider';
import SignalRProvider from './providers/SignalRProvider';
import { getCurrentUser } from './actions/authActions';
import { SessionProvider } from "next-auth/react";
import Navbar from "./nav/Navbar";

export const metadata: Metadata = {
  title: "Carsties",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ToasterProvider />
          <Navbar />
          <main className="container mx-auto px-5 pt-10">
            <SignalRProvider>{children}</SignalRProvider>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
