name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: 'emircanduman/auction-svc'
            path: 'src/AuctionService'

          - name: 'emircanduman/search-svc'
            path: 'src/SearchService'

          - name: 'emircanduman/bid-svc'
            path: 'src/BiddingService'

          - name: 'emircanduman/identity-svc'
            path: 'src/IdentityService'

          - name: 'emircanduman/notify-svc'
            path: 'src/NotificationService'

          - name: 'emircanduman/web-app'
            path: 'frontend/web-app'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ matrix.service.path }}/Dockerfile
        push: true
        tags: ${{ matrix.service.name }}:latest